<?php
/**
 * This file has been auto-generated by ORM Generator
 * 
 * @version $Rev$
 */

namespace orm;

/**
 * Auto-generated usuarios class. Add your code here.
 * 
 */
class usuarios extends \orm\base\usuarios {


	public static function getLoggin( $usuario,$pass) {

		$parametros=array('')

		$this->getByFields( )


	}


}
